server:
  port: 8085

spring:
  cloud:
    gateway:
      # If using Gateway MVC (as seen in your logs), use the 'mvc' prefix
      mvc:
        routes:
          - id: customer-service
            uri: http://localhost:8081
            predicates:
              - Path=/demo/**
            filters:
              # This matches your Java rewritePath("/demo(?<segment>/.*)", "/demo${segment}")
              - RewritePath=/demo(?<segment>/?.*), /demo$\{segment}


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  register-with-eureka: true
  fetch-registry: true